spring:
  datasource:
    username: firesin
    password: pass1@Data1
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_bot
  jpa:
    generate-ddl: true
    open-in-view: false