spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: firesin
    password: pass1@Data1
    template:
      retry:
        enabled: true
        max-attempts: 3
        initial-interval: 1000ms